const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const path = require('path');
const User = require('../models/User');
const BusinessDevelopment = require('../models/BusinessDevelopment');
require('dotenv').config({ path: path.resolve(__dirname, '../../.env') });

async function seedBD() {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/ats_db';
    console.log('Connecting to MongoDB for Business Development seeding...');
    await mongoose.connect(mongoUri);

    console.log('--- SEEDING 4 BUSINESS DEVELOPER USERS ---');
    const bdUsersData = [
      {
        name: 'Rohit Verma',
        email: 'rohit.bd@whitehorsemanpower.in',
        employeeId: 'WH000101',
        password: 'Password@123',
        role: 'bd',
        roles: ['bd'],
        isWFH: false,
        status: 'Active',
      },
      {
        name: 'Ananya Sen',
        email: 'ananya.bd@whitehorsemanpower.in',
        employeeId: 'WH000102',
        password: 'Password@123',
        role: 'bd',
        roles: ['bd'],
        isWFH: false,
        status: 'Active',
      },
      {
        name: 'Rajesh Nair',
        email: 'rajesh.bd@whitehorsemanpower.in',
        employeeId: 'WH000103',
        password: 'Password@123',
        role: 'bd',
        roles: ['bd'],
        isWFH: false,
        status: 'Active',
      },
      {
        name: 'Priya Sharma',
        email: 'priya.bd@whitehorsemanpower.in',
        employeeId: 'WH000104',
        password: 'Password@123',
        role: 'bd',
        roles: ['bd'],
        isWFH: false,
        status: 'Active',
      }
    ];

    const seededUsers = [];
    for (const u of bdUsersData) {
      let user = await User.findOne({ email: u.email });
      if (!user) {
        user = await User.create(u);
        console.log(`✅ Created BD User: ${u.name} (${u.email}) [ID: ${u.employeeId}]`);
      } else {
        user.role = 'bd';
        user.roles = ['bd'];
        user.employeeId = u.employeeId;
        user.status = 'Active';
        await user.save();
        console.log(`✅ Updated BD User: ${u.name} (${u.email})`);
      }
      seededUsers.push(user);
    }

    console.log('\n--- SEEDING REALISTIC BUSINESS DEVELOPMENT LEADS ---');
    await BusinessDevelopment.deleteMany({});

    const now = new Date();
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 11, 30);
    const yesterday = new Date(today); yesterday.setDate(yesterday.getDate() - 1);
    const daysAgo = (n) => {
      const d = new Date(today);
      d.setDate(d.getDate() - n);
      return d;
    };

    const leads = [
      // TODAY LEADS
      {
        date: today,
        executiveName: 'Rohit Verma',
        companyName: 'Razorpay Software Pvt Ltd',
        contactPerson: 'Aditi Deshmukh',
        designation: 'Head of Talent Acquisition',
        mobileNo: '9845012345',
        emailId: 'aditi.deshmukh@razorpay.com',
        city: 'Bangalore',
        industry: 'Fintech',
        source: 'LinkedIn',
        serviceOffered: 'IT Recruitment',
        callStatus: 'Connected',
        interested: 'Yes',
        requirement: 'Hiring 8 Senior Backend Engineers (Golang/Java)',
        noOfPositions: 8,
        followUpDate: daysAgo(-3),
        meetingFixed: 'Yes',
        proposalSent: 'Pending',
        agreementSent: 'No',
        clientStatus: 'Hot',
        ctc: 2400000,
        placementPercentage: 8.33,
        expectedRevenue: 1599360,
        remarks: 'Call connected smoothly. Initial screening scheduled for Friday with TA team.',
        createdBy: seededUsers[0]._id,
      },
      {
        date: today,
        executiveName: 'Ananya Sen',
        companyName: 'Swiggy Delivery Solutions',
        contactPerson: 'Karan Mehra',
        designation: 'HR Director',
        mobileNo: '9876504321',
        emailId: 'karan.mehra@swiggy.in',
        city: 'Bangalore',
        industry: 'E-commerce / Logistics',
        source: 'Naukri',
        serviceOffered: 'Permanent Recruitment',
        callStatus: 'Meeting Fixed',
        interested: 'Yes',
        requirement: 'Regional Operations Managers - 4 positions across South India',
        noOfPositions: 4,
        followUpDate: daysAgo(-2),
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'Pending',
        clientStatus: 'Hot',
        ctc: 1800000,
        placementPercentage: 8.33,
        expectedRevenue: 599760,
        remarks: 'Meeting fixed for tomorrow 3 PM. Commercial proposal shared.',
        createdBy: seededUsers[1]._id,
      },
      {
        date: today,
        executiveName: 'Rajesh Nair',
        companyName: 'Apollo Hospitals Enterprise',
        contactPerson: 'Dr. Ramesh Babu',
        designation: 'VP Medical Staffing',
        mobileNo: '9740112233',
        emailId: 'ramesh.babu@apollohospitals.com',
        city: 'Chennai',
        industry: 'Healthcare',
        source: 'Reference',
        serviceOffered: 'Healthcare Recruitment',
        callStatus: 'Connected',
        interested: 'Yes',
        requirement: 'Specialist doctors and senior nursing staff for new branch',
        noOfPositions: 15,
        followUpDate: daysAgo(-4),
        meetingFixed: 'No',
        proposalSent: 'No',
        agreementSent: 'No',
        clientStatus: 'Warm',
        ctc: 1200000,
        placementPercentage: 8.33,
        expectedRevenue: 1499400,
        remarks: 'Positive discussion. Requested rate card for permanent placements.',
        createdBy: seededUsers[2]._id,
      },
      {
        date: today,
        executiveName: 'Priya Sharma',
        companyName: 'Infosys Limited',
        contactPerson: 'Siddharth Roy',
        designation: 'Senior HR Manager - Lateral Hiring',
        mobileNo: '9988776655',
        emailId: 'siddharth.roy@infosys.com',
        city: 'Bangalore',
        industry: 'IT Services',
        source: 'Website',
        serviceOffered: 'Contract Staffing',
        callStatus: 'Call Back Later',
        interested: 'No',
        requirement: 'Contract Java full stack developers for Banking client',
        noOfPositions: 10,
        followUpDate: daysAgo(-1),
        meetingFixed: 'No',
        proposalSent: 'No',
        agreementSent: 'No',
        clientStatus: 'Cold',
        ctc: 1500000,
        placementPercentage: 8.33,
        expectedRevenue: 0,
        remarks: 'Executive in meeting. Asked to call back tomorrow at 11 AM.',
        createdBy: seededUsers[3]._id,
      },

      // YESTERDAY & THIS WEEK LEADS (2 - 7 DAYS AGO)
      {
        date: yesterday,
        executiveName: 'Rohit Verma',
        companyName: 'Zerodha Broking Limited',
        contactPerson: 'Neha Kulkarni',
        designation: 'Head of People Operations',
        mobileNo: '9820123456',
        emailId: 'neha.kulkarni@zerodha.com',
        city: 'Bangalore',
        industry: 'Fintech',
        source: 'LinkedIn',
        serviceOffered: 'Permanent Recruitment',
        callStatus: 'Converted',
        interested: 'Yes',
        requirement: 'Customer Support and Compliance Executives',
        noOfPositions: 12,
        followUpDate: null,
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'Yes',
        clientStatus: 'Converted',
        ctc: 650000,
        placementPercentage: 8.33,
        expectedRevenue: 649740,
        remarks: 'Agreement signed. Mandate shared with BPO team.',
        createdBy: seededUsers[0]._id,
      },
      {
        date: yesterday,
        executiveName: 'Ananya Sen',
        companyName: 'Tata Motors Passenger Vehicles',
        contactPerson: 'Vikas Patil',
        designation: 'DGM Talent Acquisition',
        mobileNo: '9823098765',
        emailId: 'vikas.patil@tatamotors.com',
        city: 'Pune',
        industry: 'Automobile',
        source: 'Reference',
        serviceOffered: 'Permanent Recruitment',
        callStatus: 'Connected',
        interested: 'Yes',
        requirement: 'EV Powertrain engineers & Plant managers',
        noOfPositions: 6,
        followUpDate: daysAgo(-2),
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'No',
        clientStatus: 'Hot',
        ctc: 2000000,
        placementPercentage: 8.33,
        expectedRevenue: 999600,
        remarks: 'Proposal sent with 8.33% commercial term. Awaiting contract review.',
        createdBy: seededUsers[1]._id,
      },
      {
        date: daysAgo(2),
        executiveName: 'Rajesh Nair',
        companyName: 'Fortis Healthcare Ltd',
        contactPerson: 'Dr. Archana Rao',
        designation: 'Medical Superintendent',
        mobileNo: '9740567890',
        emailId: 'archana.rao@fortishealthcare.com',
        city: 'Bangalore',
        industry: 'Healthcare',
        source: 'LinkedIn',
        serviceOffered: 'Healthcare Recruitment',
        callStatus: 'Proposal Sent',
        interested: 'Yes',
        requirement: 'Radiologists and Anaesthesiologists',
        noOfPositions: 5,
        followUpDate: daysAgo(-3),
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'Pending',
        clientStatus: 'Hot',
        ctc: 3500000,
        placementPercentage: 8.33,
        expectedRevenue: 1457750,
        remarks: 'Proposal sent for executive healthcare mandate.',
        createdBy: seededUsers[2]._id,
      },
      {
        date: daysAgo(3),
        executiveName: 'Priya Sharma',
        companyName: 'PhonePe Private Limited',
        contactPerson: 'Sunil Nair',
        designation: 'Talent Lead',
        mobileNo: '9845987612',
        emailId: 'sunil.nair@phonepe.com',
        city: 'Bangalore',
        industry: 'Fintech',
        source: 'LinkedIn',
        serviceOffered: 'IT Recruitment',
        callStatus: 'Connected',
        interested: 'Yes',
        requirement: 'DevOps & Cloud Security Engineers',
        noOfPositions: 5,
        followUpDate: daysAgo(-1),
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'Pending',
        clientStatus: 'Hot',
        ctc: 2800000,
        placementPercentage: 8.33,
        expectedRevenue: 1166200,
        remarks: 'NDA & Service Agreement sent for legal sign-off.',
        createdBy: seededUsers[3]._id,
      },
      {
        date: daysAgo(4),
        executiveName: 'Rohit Verma',
        companyName: 'Wipro Technologies',
        contactPerson: 'Suresh Kumar',
        designation: 'Resource Management Lead',
        mobileNo: '9880123789',
        emailId: 'suresh.kumar@wipro.com',
        city: 'Hyderabad',
        industry: 'IT Services',
        source: 'Website',
        serviceOffered: 'RPO',
        callStatus: 'Meeting Fixed',
        interested: 'Yes',
        requirement: 'Dedicated recruiters for US/UK shift lateral requirements',
        noOfPositions: 25,
        followUpDate: daysAgo(-2),
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'No',
        clientStatus: 'Warm',
        ctc: 800000,
        placementPercentage: 8.33,
        expectedRevenue: 1666000,
        remarks: 'Explaining our RPO framework and SLAs.',
        createdBy: seededUsers[0]._id,
      },
      {
        date: daysAgo(5),
        executiveName: 'Ananya Sen',
        companyName: 'Flipkart Internet Pvt Ltd',
        contactPerson: 'Megha Agarwal',
        designation: 'Associate Director HR',
        mobileNo: '9900112244',
        emailId: 'megha.agarwal@flipkart.com',
        city: 'Bangalore',
        industry: 'E-commerce',
        source: 'Naukri',
        serviceOffered: 'Permanent Recruitment',
        callStatus: 'Converted',
        interested: 'Yes',
        requirement: 'Supply Chain & Category Managers',
        noOfPositions: 8,
        followUpDate: null,
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'Yes',
        clientStatus: 'Converted',
        ctc: 2200000,
        placementPercentage: 8.33,
        expectedRevenue: 1466080,
        remarks: 'Agreement executed. Candidate sourcing in progress.',
        createdBy: seededUsers[1]._id,
      },
      {
        date: daysAgo(6),
        executiveName: 'Rajesh Nair',
        companyName: 'Larsen & Toubro Infotech',
        contactPerson: 'Arun Varma',
        designation: 'Head HR - Southern Region',
        mobileNo: '9845112233',
        emailId: 'arun.varma@lntinfotech.com',
        city: 'Chennai',
        industry: 'Technology / Construction',
        source: 'Reference',
        serviceOffered: 'Permanent Recruitment',
        callStatus: 'Connected',
        interested: 'Yes',
        requirement: 'Civil & Structural Design leads',
        noOfPositions: 6,
        followUpDate: daysAgo(-5),
        meetingFixed: 'No',
        proposalSent: 'Yes',
        agreementSent: 'No',
        clientStatus: 'Warm',
        ctc: 1600000,
        placementPercentage: 8.33,
        expectedRevenue: 799680,
        remarks: 'Requested profiles for 2 urgent roles before signing master agreement.',
        createdBy: seededUsers[2]._id,
      },
      {
        date: daysAgo(7),
        executiveName: 'Priya Sharma',
        companyName: 'Zomato Limited',
        contactPerson: 'Harshita Sen',
        designation: 'HR Partner',
        mobileNo: '9811223344',
        emailId: 'harshita.sen@zomato.com',
        city: 'Gurgaon',
        industry: 'Food Tech',
        source: 'LinkedIn',
        serviceOffered: 'Permanent Recruitment',
        callStatus: 'No Answer',
        interested: 'No',
        requirement: 'Sales Leads for North India',
        noOfPositions: 10,
        followUpDate: daysAgo(-1),
        meetingFixed: 'No',
        proposalSent: 'No',
        agreementSent: 'No',
        clientStatus: 'Cold',
        ctc: 900000,
        placementPercentage: 8.33,
        expectedRevenue: 0,
        remarks: 'Left voicemail and sent LinkedIn message.',
        createdBy: seededUsers[3]._id,
      },

      // EARLIER THIS MONTH & PAST MONTH LEADS (8 - 30 DAYS AGO)
      {
        date: daysAgo(10),
        executiveName: 'Rohit Verma',
        companyName: 'Accenture India',
        contactPerson: 'Prateek Jain',
        designation: 'Lead Recruiter',
        mobileNo: '9820011223',
        emailId: 'prateek.jain@accenture.com',
        city: 'Bangalore',
        industry: 'IT Services',
        source: 'LinkedIn',
        serviceOffered: 'NEXORA ATS',
        callStatus: 'Converted',
        interested: 'Yes',
        requirement: 'Custom ATS Integration for recruitment workflow',
        noOfPositions: 1,
        followUpDate: null,
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'Yes',
        clientStatus: 'Converted',
        ctc: 300000,
        placementPercentage: 100,
        expectedRevenue: 300000,
        remarks: 'Annual ATS enterprise subscription closed.',
        createdBy: seededUsers[0]._id,
      },
      {
        date: daysAgo(12),
        executiveName: 'Ananya Sen',
        companyName: 'HDFC Bank Limited',
        contactPerson: 'Deepak Joshi',
        designation: 'Zonal HR Head',
        mobileNo: '9822334455',
        emailId: 'deepak.joshi@hdfcbank.com',
        city: 'Mumbai',
        industry: 'Banking & Financial',
        source: 'Reference',
        serviceOffered: 'Permanent Recruitment',
        callStatus: 'Converted',
        interested: 'Yes',
        requirement: 'Branch Managers & Relationship Executives',
        noOfPositions: 20,
        followUpDate: null,
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'Yes',
        clientStatus: 'Converted',
        ctc: 850000,
        placementPercentage: 8.33,
        expectedRevenue: 1416100,
        remarks: 'Signed annual empanelment agreement.',
        createdBy: seededUsers[1]._id,
      },
      {
        date: daysAgo(15),
        executiveName: 'Rajesh Nair',
        companyName: 'Manipal Hospitals Group',
        contactPerson: 'Sumanth Reddy',
        designation: 'Head Talent Acquisition',
        mobileNo: '9845334455',
        emailId: 'sumanth.reddy@manipalhospitals.com',
        city: 'Bangalore',
        industry: 'Healthcare',
        source: 'Naukri',
        serviceOffered: 'Healthcare Recruitment',
        callStatus: 'Converted',
        interested: 'Yes',
        requirement: 'Emergency Care Physicians & Duty Doctors',
        noOfPositions: 10,
        followUpDate: null,
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'Yes',
        clientStatus: 'Converted',
        ctc: 1800000,
        placementPercentage: 8.33,
        expectedRevenue: 1499400,
        remarks: 'Empanelment active. 4 doctor profiles submitted.',
        createdBy: seededUsers[2]._id,
      },
      {
        date: daysAgo(18),
        executiveName: 'Priya Sharma',
        companyName: 'ICICI Lombard General Insurance',
        contactPerson: 'Anil Kapoor',
        designation: 'VP Human Resources',
        mobileNo: '9820998877',
        emailId: 'anil.kapoor@icicilombard.com',
        city: 'Mumbai',
        industry: 'Insurance',
        source: 'Website',
        serviceOffered: 'Permanent Recruitment',
        callStatus: 'Connected',
        interested: 'Yes',
        requirement: 'Claims Underwriters & Risk Assessors',
        noOfPositions: 6,
        followUpDate: daysAgo(-10),
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'Pending',
        clientStatus: 'Hot',
        ctc: 1400000,
        placementPercentage: 8.33,
        expectedRevenue: 699720,
        remarks: 'Under final management review for contract approval.',
        createdBy: seededUsers[3]._id,
      },
      {
        date: daysAgo(22),
        executiveName: 'Rohit Verma',
        companyName: 'Cognizant Technology Solutions',
        contactPerson: 'Gautam Menon',
        designation: 'Director Recruitment',
        mobileNo: '9840123987',
        emailId: 'gautam.menon@cognizant.com',
        city: 'Chennai',
        industry: 'IT Services',
        source: 'LinkedIn',
        serviceOffered: 'Contract Staffing',
        callStatus: 'Connected',
        interested: 'Yes',
        requirement: 'SAP S/4 HANA Functional Consultants',
        noOfPositions: 6,
        followUpDate: daysAgo(-5),
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'No',
        clientStatus: 'Warm',
        ctc: 2500000,
        placementPercentage: 8.33,
        expectedRevenue: 1249500,
        remarks: 'Rate agreement discussed. Follow-up scheduled.',
        createdBy: seededUsers[0]._id,
      },
      {
        date: daysAgo(25),
        executiveName: 'Ananya Sen',
        companyName: 'BigBasket (Supermarket Grocery)',
        contactPerson: 'Tanvi Shah',
        designation: 'HR Lead - Fulfillment',
        mobileNo: '9988001122',
        emailId: 'tanvi.shah@bigbasket.com',
        city: 'Bangalore',
        industry: 'E-commerce',
        source: 'Naukri',
        serviceOffered: 'Permanent Recruitment',
        callStatus: 'Converted',
        interested: 'Yes',
        requirement: 'Warehouse Operation Heads & Inventory Leads',
        noOfPositions: 8,
        followUpDate: null,
        meetingFixed: 'Yes',
        proposalSent: 'Yes',
        agreementSent: 'Yes',
        clientStatus: 'Converted',
        ctc: 1100000,
        placementPercentage: 8.33,
        expectedRevenue: 733040,
        remarks: 'Contract signed and candidate pipeline active.',
        createdBy: seededUsers[1]._id,
      }
    ];

    const inserted = await BusinessDevelopment.insertMany(leads);
    console.log(`=======================================================`);
    console.log(`  BD SEEDING COMPLETE: ${inserted.length} LEADS INSERTED!`);
    console.log(`=======================================================`);

    await mongoose.disconnect();
    console.log('MongoDB disconnected.');
  } catch (err) {
    console.error('Error seeding BD:', err);
    process.exit(1);
  }
}

seedBD();
